name: Python package

on: [push]

jobs:
  build1:
    env: 
    DATABASE_HOSTNAME: dpg-da1kuc67bikc739br9cg-a.singapore-postgres.render.com
    DATABASE_PORT: 5432
    DATABASE_PASSWORD: DflNUFkDn5tkFyADSsppYLrrpsqDKgc7
    DATABASE_NAME: db_holiday_hostels
    DATABASE_USERNAME: murali22
    SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    ALGORITHM: HS256
    ACCESS_TOKEN_EXPIRE_MINUTES: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.12'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name:  update pip
        run: python -m pip install --upgrade pip
      - name: install dependcies
        run: pip install -r requirements.txt
      - name: test with pytest 
        run: |
          pip install pytest
          pytest -v 

